version: 2.1

parameters:
  foo:
    type: boolean
    default: true
  bar:
    type: boolean
    default: false

jobs:
  codecoverage:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: echo codecoverage
  binary-size:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: echo binary-size

workflows:
  version: 2
  android-navigation:
    when: << pipeline.parameters.bar >>
    jobs:
      - codecoverage
      - binary-size
  android-maps:
    when: << pipeline.parameters.foo >>
    jobs:
      - codecoverage
      - binary-size