version: 2.1

parameters:
  foo:
    type: integer
    default: 1
  bar:
    type: integer
    default: 0
  foobar:
    type: integer
    default: 1

jobs:
  codecoverage:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo codecoverage
                   echo << pipeline.parameters.foo >>
                   echo << pipeline.parameters.bar >>
                   let "pipelines.parameters.foobar = << pipeline.parameters.foo >> * << pipeline.parameters.bar >>"
                   echo << pipeline.parameters.foobar >>
  binary-size:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo binary-size
                   echo << pipeline.parameters.bar >>
                   echo << pipeline.parameters.foo >>
                   let "pipelines.parameters.foobar = << pipeline.parameters.foo >> * << pipeline.parameters.bar >>"
                   echo << pipeline.parameters.foobar >>
workflows:
  version: 2
  android-navigation:
    when: -|
      << pipeline.parameters.foobar >>
    jobs:
      - codecoverage
      - binary-size:
          requires: 
            - codecoverage
  android-maps:
    when: << pipeline.parameters.foo >>
    jobs:
      - binary-size    
      - codecoverage:
          requires:
            - binary-size