version: 2.1

parameters:
  foo:
    type: boolean
    default: true
  bar:
    type: boolean
    default: false

jobs:
  codecoverage:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo codecoverage
                   echo << pipeline.parameters.foo >>
                   echo << pipeline.parameters.bar >>
  binary-size:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo binary-size
                   echo << pipeline.parameters.bar >>
                   echo << pipeline.parameters.foo >>
workflows:
  version: 2
  android-navigation:
    when: |
      << pipeline.parameters.bar >>
      << pipeline.parameters.foo >>
    jobs:
      - codecoverage
      - binary-size:
          requires: 
            - codecoverage
  android-maps:
    when: << pipeline.parameters.foo >>
    jobs:
      - binary-size    
      - codecoverage:
          requires:
            - binary-size