version: 2.1
jobs:
  build-linux:
    docker:
      - image: node
    steps:
        - run: mkdir -p app/linux
        - run:
            name: Generate app
            command: echo app >> app/linux/app.linux
        - run: cd ~/project/app && pwd && ls
          # Edit below here
        - persist_to_workspace: 
            root: /tmp/my_workspace
            paths: linux

  build-windows:
    docker:
      - image: node # use your imagination, using all linux/docker for ease-of-use
    steps:
        - run: mkdir -p app/windows
        - run:
            name: Generate app
            command: echo app >> app/windows/app.windows
        - run: cd ~/project/app && pwd && ls
          # Edit below here
        - persist_to_workspace: 
            root: /tmp/my_workspace
            paths: windows

  build-mac:
      docker:
        - image: node # use your imagination, using all linux/docker for ease-of-use
      steps:
        - run: mkdir -p app/mac
        - run:
            name: Generate app
            command: echo app >> app/mac/app.mac
        - run: cd ~/project/app && pwd && ls
          # Edit below here
        - persist_to_workspace: 
            root: /tmp/my_workspace
            paths: mac

  deploy:
      docker:
        - image: node
      steps:
        - attach_workspace:
            at: /tmp/workspaces
        - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
            path: app
            destination: apps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-linux
      - build-mac
      - build-windows
      - deploy:
          requires:
            - build-linux
            - build-mac
            - build-windows