version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/       
      - deploy:
          requires:
            - test
          filters:
            tags:
              only:
                - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
            branches:
              only: development                