version: 2.1

jobs:
    build:
        docker: 
            - image: circleci/node 
        steps:
            - checkout
            - run: "echo \"This command will generate sample Jest and Python JUnit XML test results\"\necho \"----------------------------------------------------------------------------------------------------\"\necho \"Working directory is: $(pwd)\"\necho \"Sample Jest results will be stored in: ~/project/results/jest (creating it if it does not exist...)\"\nmkdir -p ~/project/results/jest\ncat \\<< EOF > ~/project/results/jest/junit.xml\n<testsuites name=\"jest tests\">\n  <testsuite name=\"undefined\" errors=\"0\" failures=\"0\" skipped=\"0\" timestamp=\"2018-05-16T22:26:25\" time=\"4.21\" tests=\"1\">\n    <testcase classname=\" renders without crashing\" name=\" renders without crashing\" time=\"2.879\">\n    </testcase>\n  </testsuite>\n</testsuites>\nEOF\necho \"----------------------------------------------------------------------------------------------------\"\necho \"Working directory is: $(pwd)\"\necho \"Sample Python results will be stored in: ~/project/results/python (creating it if it does not exist...)\"\nmkdir -p ~/project/results/python\ncat \\<< EOF > ~/project/results/python/junit.xml\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<testsuite errors=\"0\" failures=\"0\" name=\"test_api.APITestCase-20180507233023\" skipped=\"0\" tests=\"9\" time=\"2.250\">\n  <testcase classname=\"test_api.APITestCase\" name=\"test_404\" time=\"0.153\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_anonymous\" time=\"0.070\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_bad_auth\" time=\"0.192\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_comments\" time=\"0.523\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_no_auth\" time=\"0.072\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_posts\" time=\"0.559\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_token_auth\" time=\"0.193\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_unconfirmed_account\" time=\"0.190\"/>\n  <testcase classname=\"test_api.APITestCase\" name=\"test_users\" time=\"0.297\"/>\n  <system-out>\n<![CDATA[]]>\t</system-out>\n  <system-err>\n<![CDATA[]]>\t</system-err>\n</testsuite>\nEOF\necho \"----------------------------------------------------------------------------------------------------\"\necho \"Sample test results have been stored in ~/project/results/jest and ~/project/results/python\"\n"
            - store_test_results:
                path: ~/project/results/results.xml
            - run:
                name: Run Hello test
                command: |
                    bash src/test_hello.sh
            - run:
                name: Run Goodbye test
                command: |
                    bash src/test_goodbye.sh

workflows:
    build_and_test:
        jobs:
            - build
